# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_language_version:
    python: python3.10
# For the template repo only
ci:
    skip: [ggshield, pymarkdown]
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: debug-statements
          - id: requirements-txt-fixer
          - id: name-tests-test
    - repo: https://github.com/thlorenz/doctoc
      rev: v2.2.0
      hooks:
          - id: doctoc
    - repo: https://github.com/asottile/pyupgrade
      rev: v3.19.1
      hooks:
          - id: pyupgrade
            args: [--py310-plus]
    - repo: https://github.com/jackdewinter/pymarkdown
      rev: v0.9.29
      hooks:
          - id: pymarkdown
            pass_filenames: false
            args: [-d, "MD041, MD013", scan, -r, .]
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.11.4
      hooks:
          # Run the linter.
          - id: ruff
            args: [--target-version, py310]
          # Run the formatter.
          - id: ruff-format
            args: [--target-version, py310]
    - repo: https://github.com/pycqa/bandit
      rev: 1.8.3
      hooks:
          - id: bandit
            additional_dependencies:
                - bandit[toml]
            args:
                - --configfile=pyproject.toml
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.15.0
      hooks:
          - id: mypy
    - repo: https://github.com/AleksaC/hadolint-py
      rev: v2.12.1b3
      hooks:
          - id: hadolint
    - repo: https://github.com/gitguardian/ggshield
      rev: v1.38.1
      hooks:
          - id: ggshield
    - repo: https://github.com/codespell-project/codespell
      rev: v2.4.1
      hooks:
          - id: codespell
