# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# For the template repo only
ci:
    skip: [hadolint-docker, docker-ggshield]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: requirements-txt-fixer
    -   id: name-tests-test
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.2.0
    hooks:
    -   id: setup-cfg-fmt
-   repo: https://github.com/thlorenz/doctoc
    rev: v2.2.0
    hooks:
    -   id: doctoc
-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.33.0
    hooks:
    -   id: markdownlint-docker
        args: [--disable, MD041, --]
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args: [--py310-plus]
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
    -   id: mypy
        additional_dependencies: [types-all]
-   repo: https://github.com/hadolint/hadolint
    rev: v2.12.1-beta
    hooks:
      - id: hadolint-docker
-   repo: https://github.com/gitguardian/ggshield
    rev: v1.14.4
    hooks:
    -   id: docker-ggshield
